/**
 * ARCHIVO GENERADO — no editar a mano.
 *
 * Lo produce `node scripts/datos/construir-catalogo-ambulancias.mjs` desde
 * `data/procesado/ambulancias.json` (que a su vez sale del CSV de transporte
 * especial de pacientes de la Secretaria de Salud). Cualquier cambio aqui se
 * pierde en la siguiente corrida: para cambiar el contenido se cambia la
 * fuente o su transformador.
 *
 * La transformacion es un renombre de campos 1:1:
 *
 *     email        -> correo
 *     basico       -> tab   (Transporte Asistencial Basico)
 *     medicalizado -> tam   (Transporte Asistencial Medicalizado)
 *
 * Se compila, en vez de leerse de data/, por lo mismo que
 * `sedes/catalogo.generado.ts`: sin Supabase el modulo tiene que seguir
 * verificando afiliaciones, y `dist/` no lleva data/ adentro.
 *
 * Generado: 2026-08-23
 * Fuente:   data/procesado/ambulancias.json
 *           (Secretaria de Salud de Bogota — transporte especial de pacientes, corte 01/07/2026)
 */

import type { OperadorAmbulancia } from './tipos';

/**
 * 225 prestadores de transporte asistencial de Bogota.
 * 112 con marca TAB, 53 con TAM. Ver data/CATALOGO.md.
 *
 * `nit` va en null en las 225: la fuente publica razon social, sede,
 * direccion, telefono y correo, pero NO el NIT.
 */
export const AMBULANCIAS_CATALOGO: OperadorAmbulancia[] = [
  {
    "prestador": "333 ASISTENCIAS MEDICAS SAS SIGLA 333 AM",
    "sede": "333 ASISTENCIAS MEDICAS SAS SIGLA 333 AM",
    "direccion": "DIAGONAL 79 B 62-21 LOCAL 1 PISO 1",
    "telefono": "3223611646",
    "correo": "333asistenciasmedicas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "ADMINISTRADORA CLINICA LA COLINA SAS",
    "sede": "ADMINISTRADORA CLINICA LA COLINA SAS",
    "direccion": "CALLE 167 72 07 PISO 1,PISO 2 (EXCEPTO CONSULTORIOS 215 Y 216),PISO 3, PISO 4,PISO 5,PISO 6,PISO 7 Y PISO 8",
    "telefono": "6013905355",
    "correo": "notificacionesclc@clinicadelcountry.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "ADMINISTRADORA COUNTRY S.A.S",
    "sede": "CLINICA DEL COUNTRY IPS",
    "direccion": "CRA 16 # 82 57",
    "telefono": "6013905099",
    "correo": "notificacionescdc@clinicadelcountry.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "AEROMAS SAS",
    "sede": "AEROMAS SAS",
    "direccion": "Avenida Calle 26 113 81 Aeropuerto Internacional El Dorado En 6 Hg 15 Piso 1 Nzag",
    "telefono": "3175867106",
    "correo": "habilitacion@aeromas.com.co",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "aerosanidad sas",
    "sede": "aerosanidad sas",
    "direccion": "CR 28A #71-94 PISO 1",
    "telefono": "3507256387",
    "correo": "gerencia@aerosanidadsas.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "Alianza Codigo Rojo IPS SAS",
    "sede": "Alianza Código Rojo IPS SAS",
    "direccion": "Carrera 18#56 a-46 SUR",
    "telefono": "3227373252",
    "correo": "medicalsaludcodigorojo@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "ALIANZA DE AMBULANCIAS MEDICA SAS",
    "sede": "ALIANZA DE AMBULANCIAS MEDICA S.A.S",
    "direccion": "CALLE 102 A # 70 B - 80",
    "telefono": "6245072 - 6240648",
    "correo": "alianzaamedica@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "ALIANZA DE AMBULANCIAS MEDICA SAS",
    "sede": "ALIANZA DE AMBULANCIAS MEDICA S.A.S",
    "direccion": "CALLE 102 A # 70 B - 80",
    "telefono": "6245072 - 6240648",
    "correo": "alianzaamedica@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "ambucol sociedad por acciones simplificadas - ambucol sas",
    "sede": "ambucol sociedad por acciones simplificadas - ambucol sas",
    "direccion": "Calle 151A # 92- 91",
    "telefono": "4711757",
    "correo": "ambucol@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS AEREAS DE COLOMBIA S.A.S.",
    "sede": "AMBULANCIAS AEREAS DE COLOMBIA S.A.S.",
    "direccion": "Carrera 103 # 26-92 Int 09 hangar 182",
    "telefono": "3125488322 3108814575",
    "correo": "direccionmedica@ambulanciasaereasdecolombia.com administracion@ambulanciasaereasdecolombia.com",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS EMERGENCIAS & SERVICIOS ASISTENCIALES SAS SIGLA AMBULANCIAS E.S.A S.A.S",
    "sede": "AMBULANCIAS E.S.A S.A.S SEDE BOGOTA",
    "direccion": "CALLE 41 B SUR Nº 79 G 21 PISO 1",
    "telefono": "3133105207",
    "correo": "AMBULANCIASESAS@GMAIL.COM",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS FUERZA VITAL SAS",
    "sede": "AMBULANCIAS FUERZA VITAL SAS",
    "direccion": "CARRERA 81 A Nº 60-42 SUR PISO 1",
    "telefono": "3118327515",
    "correo": "ambulanciasfuerzavitalsas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS INTEGRALES DE COLOMBIA A.I.C. SAS",
    "sede": "AMBULANCIAS INTEGRALES DE COLOMBIA A.I.C. SAS",
    "direccion": "CALLE 37 SUR # 68 I 23 piso 1",
    "telefono": "7652655",
    "correo": "yulypacan@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS MEDICAS PROFESIONALES S.A.S",
    "sede": "AMBULANCIAS MEDICAS PROFESIONALES S.A.S",
    "direccion": "CARRERA 65 B # 74 A 14",
    "telefono": "6205105, 2250962, 2404330",
    "correo": "ambulanciasmedicas@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS PRIMEROS AUXILIOS LTDA",
    "sede": "AMBULANCIAS PRIMEROS AUXILIOS LTDA",
    "direccion": "KR 32 B # 2 43",
    "telefono": "2770977",
    "correo": "operaciones@apa.net.co",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS PRIMEROS AUXILIOS LTDA",
    "sede": "AMBULANCIAS PRIMEROS AUXILIOS LTDA",
    "direccion": "KR 32 B # 2 43",
    "telefono": "2770977",
    "correo": "operaciones@apa.net.co",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS SEGUNDOS DE VIDA SAS",
    "sede": "AMBULANCIAS SEGUNDOS DE VIDA SEDE BOGOTA",
    "direccion": "CALLE 69 A BIS # 90 - 67 PISO 1",
    "telefono": "3102244480",
    "correo": "ambulanciassegundosdevida@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS Y SERVICIOS MEDICOS S A",
    "sede": "AMBULANCIAS Y SERVICIOS MEDICOS S A",
    "direccion": "CL 62 # 26 29",
    "telefono": "2359377",
    "correo": "asmambulancias@yahoo.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "AMBULANCIAS Y SERVICIOS MEDICOS S A",
    "sede": "AMBULANCIAS Y SERVICIOS MEDICOS S A",
    "direccion": "CL 62 # 26 29",
    "telefono": "2359377",
    "correo": "asmambulancias@yahoo.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "Ambulife sas",
    "sede": "Ambulife sas",
    "direccion": "CARRERA 82 Nº 70 A 03 SUR P1",
    "telefono": "3144937618",
    "correo": "AMBULIFESAS@GMAIL.COM",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "Ambulife sas",
    "sede": "Ambulife sas",
    "direccion": "CARRERA 82 Nº 70 A 03 SUR P1",
    "telefono": "3144937618",
    "correo": "AMBULIFESAS@GMAIL.COM",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "AMBUMED SAS",
    "sede": "AMBUMED SAS SEDE BOGOTA",
    "direccion": "CALLE 49 A SUR 28-36 PISO 1",
    "telefono": "3002089148",
    "correo": "ambumedsas.724@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AMBUSALUD RCP SAS",
    "sede": "AMBUSALUD RCP",
    "direccion": "AK 72 N 74 A 46",
    "telefono": "(+57) 3138432498- 3208906255 (031)7045807",
    "correo": "ambusaludrcp@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AMBU-SANAR S.A.S SIGLA AMBUSAS",
    "sede": "AMBU-SANAR S.A.S SIGLA AMBUSAS",
    "direccion": "CRA 69 K # 79 - 67 Piso 1",
    "telefono": "3212180015",
    "correo": "ambusanar2021@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "AMBU-SANAR S.A.S SIGLA AMBUSAS",
    "sede": "AMBU-SANAR S.A.S SIGLA AMBUSAS",
    "direccion": "CRA 69 K # 79 - 67 Piso 1",
    "telefono": "3212180015",
    "correo": "ambusanar2021@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "AMBUSURE IPS S.A.S.",
    "sede": "AMBUSURE IPS",
    "direccion": "TR 77 C 47-16 P1",
    "telefono": "3214882104",
    "correo": "ambusureips@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "APPSEMI S.A.S",
    "sede": "APPSEMI S.A.S",
    "direccion": "CL 79B # 29B - 44 Piso 1",
    "telefono": "3237385185",
    "correo": "appsemiambulancias@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "APPSEMI S.A.S",
    "sede": "APPSEMI S.A.S",
    "direccion": "CL 79B # 29B - 44 Piso 1",
    "telefono": "3237385185",
    "correo": "appsemiambulancias@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "ASISTENCIA MEDICA EN LINEA SAS",
    "sede": "ASISTENCIA MEDICA EN LINEA SAS",
    "direccion": "CRA 14 N° 24 17 SUR PISO 1",
    "telefono": "2782446",
    "correo": "asismed.enlinea@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "ASISTENCIA MEDICA EN LINEA SAS",
    "sede": "ASISTENCIA MEDICA EN LINEA SAS",
    "direccion": "CRA 14 N° 24 17 SUR PISO 1",
    "telefono": "2782446",
    "correo": "asismed.enlinea@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "ASISTENCIA MEDICA ESPECIAL EN SALUD IPS SAS SIGLA AMESALUD IPS SAS",
    "sede": "ASISTENCIA MEDICA ESPECIAL EN SALUD IPS SAS SIGLA AMESALUD IPS SAS",
    "direccion": "CALLE 42 SUR 78M 35, PRIMER PISO",
    "telefono": "3045779362",
    "correo": "ipsservices2024@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "ASMED SALUD SAS",
    "sede": "ASMED SALUD SAS",
    "direccion": "Calle 5 Sur No 71d-14",
    "telefono": "3164541759 - 3173816515",
    "correo": "asmedsaludsas@gmail.com",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "ASOCIACION DE AMIGOS CONTRA EL CANCER PROSEGUIR",
    "sede": "PROSEGUIR SEDE 3",
    "direccion": "CARRERA 16 No 59-04 / 54",
    "telefono": "5557080 EXT 1026",
    "correo": "calidad@proseguir.org",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AYP AMBULANCIAS SAS",
    "sede": "AYP AMBULANCIAS SAS",
    "direccion": "CARRERA 19 # 56-31 SUR PISO 1",
    "telefono": "3103020981",
    "correo": "aypambulancias.sas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AYUDA MEDICA DOMICILIARIA Y EMPRESARIAL SOLUCIONES EN SALUD OCUPACIONAL S A S",
    "sede": "AYUDA MEDICA DOMICILIARIA Y EMPRESARIAL SOLUCIONES EN SALUD OCUPACIONAL S A S",
    "direccion": "Carrera 69F # 64F-43 Piso 1",
    "telefono": "601 3907495 3176681051",
    "correo": "habilitacion@ayudamedica.com.co gerencia@ayudamedica.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "AYUDA MEDICA TERRITORIAL EN AMBULANCIAS AYMEDT AMBULANCIAS LTDA",
    "sede": "AYUDA MEDICA TERRITORIAL EN AMBULANCIAS AYMEDT AMBULANCIAS LTDA",
    "direccion": "KR 20 # 20 41 SUR PISO 1",
    "telefono": "3132072421",
    "correo": "aymedtambulancias@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "AYUDA MEDICA TERRITORIAL EN AMBULANCIAS AYMEDT AMBULANCIAS LTDA",
    "sede": "AYUDA MEDICA TERRITORIAL EN AMBULANCIAS AYMEDT AMBULANCIAS LTDA",
    "direccion": "KR 20 # 20 41 SUR PISO 1",
    "telefono": "3132072421",
    "correo": "aymedtambulancias@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "Blue health colombia sas",
    "sede": "Blue health colombia sas",
    "direccion": "CALLE 94A No 58 - 40 BG P 1",
    "telefono": "3164339311",
    "correo": "bluehealthsas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "Blue health colombia sas",
    "sede": "Blue health colombia sas",
    "direccion": "CALLE 94A No 58 - 40 BG P 1",
    "telefono": "3164339311",
    "correo": "bluehealthsas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "BLUE MEDICALL AMBULANCE SAS",
    "sede": "BLUE MEDICALL AMBULANCE SAS",
    "direccion": "CARRERA 30 No 1-07 PISO 1",
    "telefono": "3103194526",
    "correo": "blueemedicall2022@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "CAJA COLOMBIANA DE SUBSIDIO FAMILIAR COLSUBSIDIO",
    "sede": "CLINICA INFANTIL COLSUBSIDIO",
    "direccion": "CALLE 66 # 10 - 48",
    "telefono": "7467310 extensión 75210",
    "correo": "calidad.colsubsidio@colsubsidio.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CAJA COLOMBIANA DE SUBSIDIO FAMILIAR COLSUBSIDIO",
    "sede": "CENTRO MEDICO COLSUBSIDIO QUIROGA",
    "direccion": "CL 38 SUR # 18 30",
    "telefono": "7607461 Ext. 101",
    "correo": "calidad.colsubsidio@colsubsidio.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CAJA DE COMPENSACIÓN FAMILIAR CAFAM",
    "sede": "Centro de Atención en Salud Cafam Floresta",
    "direccion": "AK 68 No.90-88",
    "telefono": "5550700 ext 12017-12015",
    "correo": "calidadsalud@cafam.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CAJA DE COMPENSACIÓN FAMILIAR CAFAM",
    "sede": "Centro de Atención en Salud Cafam Suba",
    "direccion": "KR 113 C # 142 A 98",
    "telefono": "5550700 ext 12017-12015",
    "correo": "calidadsalud@cafam.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CDF SERVICIO OPORTUNO DE TRANSPORTE EN AMBULANCIA SAS",
    "sede": "CDF SERVICIO OPORTUNO DE TRANSPORTE EN AMBULANCIA SAS",
    "direccion": "CARRERA 79 B SUR 41 F 57 PISO 1",
    "telefono": "3103287816",
    "correo": "SERVICIOOPORTUNODEEMERGENCIA@GMAIL.COM",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "CENTRO INTEGRAL DE INNOVACIÓN Y TECNOLOGÍA CLÍNICA ONKOS S.A.S",
    "sede": "CENTRO INTEGRAL DE INNOVACIÓN Y TECNOLOGÍA CLÍNICA ONKOS S.A.S",
    "direccion": "Diagonal 33 Bis A # 14 37",
    "telefono": "3208400 ext 290 - 3203037398",
    "correo": "dianaespinosanarvaez@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "CENTROS MEDICOS COLSANITAS S.A.S",
    "sede": "CENTRAL DE URGENCIAS NORTE",
    "direccion": "Calle 163 A 22 22",
    "telefono": "6466060 Ext 5719469",
    "correo": "mnempeque@epssanitas.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CENTROS MEDICOS COLSANITAS S.A.S",
    "sede": "UNIDAD DE URGENCIAS PUENTE ARANDA",
    "direccion": "Carrera 62 14 41",
    "telefono": "6466060",
    "correo": "mnempeque@epssanitas.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLÍNICA COLSANITAS S.A.",
    "sede": "CLINICA REINA SOFIA",
    "direccion": "Cra 21 127 03 / Ac 127 21 60 Cn 106 Al 111, 202, 203, 211, 214, 225, 316, 322, 324, 410 A Y B, 424",
    "telefono": "6466060 ext 5717528",
    "correo": "calidadclinica@colsanitas.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLÍNICA COLSANITAS S.A.",
    "sede": "CLINICA UNIVERSITARIA COLOMBIA",
    "direccion": "Cl236646Int5Int4Cs201Al209,3P501,503,505Al507,509,703,704,706,708,710,714Al717,719Al723,725Al727,803,811,813,814,816A818,822A825,903,907,911,915,919A921,927,1004,1009,1013,1015Al1019,1103,1119,1121,1122,1203,1206,1209,1210,1214A12161218A1220122212251226",
    "telefono": "5948650",
    "correo": "calidadclinica@colsanitas.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLÍNICA COLSANITAS S.A.",
    "sede": "CLINICA REINA SOFIA PEDIATRICA Y MUJER",
    "direccion": "Ac 127 No 20 - 56",
    "telefono": "6466060",
    "correo": "calidadclinica@colsanitas.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLÍNICA COLSANITAS S.A.",
    "sede": "CENTRO MEDICO COLSANITAS EL DORADO",
    "direccion": "AVENIDA CALLE 26 # 113 - 90",
    "telefono": "6466060",
    "correo": "calidadclinica@colsanitas.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "CLÍNICA COLSANITAS S.A.",
    "sede": "CLÍNICA INFANTIL SANTA MARÍA DEL LAGO",
    "direccion": "CL 73 A NO. 76 66",
    "telefono": "3406767",
    "correo": "calidadclinica@colsanitas.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA DE LA MUJER S.A.S.",
    "sede": "CLINICA DE LA MUJER",
    "direccion": "KR 19 C # 91 17",
    "telefono": "6161799- 3506005706",
    "correo": "Elizabeth.Parada@QuironSalud.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA DE MARLY S.A",
    "sede": "CLINICA DE MARLY",
    "direccion": "CL 50 # 9 67",
    "telefono": "3436600",
    "correo": "cmarly@clinicademarly.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA DE MARLY S.A",
    "sede": "CLINICA DE MARLY",
    "direccion": "CL 50 # 9 67",
    "telefono": "3436600",
    "correo": "cmarly@clinicademarly.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLÍNICA DE NUESTRA SEÑORA DE LA PAZ",
    "sede": "CLINICA DE NUESTRA SEÑORA DE LA PAZ",
    "direccion": "CARRERA 69 # 12 - 75",
    "telefono": "2921277",
    "correo": "gestorcalidad@cllapaz.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA DEL OCCIDENTE S.A.",
    "sede": "CLINICA DEL OCCIDENTE S.A.",
    "direccion": "AV DE LAS AMERICAS # 71 C 29",
    "telefono": "4254620 Ext 150",
    "correo": "calidad@clinicadeloccidente.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA DEL TRABAJADOR SAS",
    "sede": "CLININORTE 161",
    "direccion": "Ac 161 16 C 39/51",
    "telefono": "3188604159",
    "correo": "gerencia@clinicadeltrabajador.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA JUAN N CORPAS LTDA",
    "sede": "CLINICA JUAN N CORPAS LTDA",
    "direccion": "KR 111 # 159 A 61",
    "telefono": "6865000 Ext.1060 - 3233103491",
    "correo": "dir_calidad@clinicajuanncorpas.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA LOS NOGALES SAS",
    "sede": "CLINICA LOS NOGALES SAS",
    "direccion": "Calle 95 N° 23-61",
    "telefono": "5937000 Ext: 2045 / 2036 Cel: 3014199316",
    "correo": "notificacioneslegales@clinicanogales.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA MEDICAL SAS",
    "sede": "CLINICA MEDICAL S.A.S.",
    "direccion": "Calle 36 Sur No 77 - 33",
    "telefono": "4505200 3168757999",
    "correo": "coor.calidad@clinicamedical.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA NUEVA EL LAGO S.A.S.",
    "sede": "CLINICA NUEVA EL LAGO S.A.S - SEDE CALLE 76",
    "direccion": "Calle 76 No. 15-55 Sótano 1 (S1-1 S1-2 S1-6 S1-7 S1-8 S1-9 S1-10 S1-11) Pisos 1-2-3-4-5-6-7-8-9",
    "telefono": "3078061 - 3123459128",
    "correo": "info@clinicanuevaellago.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CLINICA NUEVA EL LAGO S.A.S.",
    "sede": "CLINICA NUEVA EL LAGO S.A.S - SEDE CALLE 76",
    "direccion": "Calle 76 No. 15-55 Sótano 1 (S1-1 S1-2 S1-6 S1-7 S1-8 S1-9 S1-10 S1-11) Pisos 1-2-3-4-5-6-7-8-9",
    "telefono": "3078061 - 3123459128",
    "correo": "info@clinicanuevaellago.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Clínica Santa Mónica de Bogotá SAS",
    "sede": "CLÍNICA AZUL",
    "direccion": "KR 49 D # 91 33, piso 1,3,4,5,6,7,y 2 ala Norte",
    "telefono": "3184871071",
    "correo": "calidadca@clinicaazul.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "COLCHARTER IPS SAS",
    "sede": "COLCHARTER IPS SAS",
    "direccion": "Autopista Norte Km 16, Via Guaymaral Lote 9 , Manzana A / Aeropuerto Guaymaral",
    "telefono": "3176409979",
    "correo": "direccionmedica@colcharter.com contabilidad@colcharter.com",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "COMUNIDAD HERMANAS HOSPITALARIAS DEL SAGRADO CORAZON DE JESUS",
    "sede": "CLINICA LA INMACULADA",
    "direccion": "CRA 7 # 68 70",
    "telefono": "5870366",
    "correo": "inmaculada@clinicalainmaculada.org",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CONCESION PARQUE SALITRE MAGICO SAS siglas SAMA PARK SAS",
    "sede": "CONCESION PARQUE SALITRE MAGICO SAS siglas SAMA PAK SAS",
    "direccion": "AC 63 # 60-80",
    "telefono": "6605000 -3122320086",
    "correo": "contacto@salitremagico.com.co/sermedico@salitremagico.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "CONGREGACION DE DOMINICAS DE SANTA CATALINA DE SENA",
    "sede": "CLINICA NUEVA",
    "direccion": "CL 45 F # 16 A 11",
    "telefono": "3274444 ext 515-530",
    "correo": "calidad@clinicanueva.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CONGREGACION DE LAS HERMANAS DE LA CARIDAD DOMINICAS DE LA PRESENTACION DE LA SANTISIMA VIRGEN",
    "sede": "CLINICA PALERMO",
    "direccion": "Calle 45 C No. 22-02",
    "telefono": "7454500",
    "correo": "GestiondeCalidad@clinicapalermo.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Coomeva Medicina Prepagada S.A",
    "sede": "CENTRO MEDICO COOMEVA MEDICINA PREPAGADA",
    "direccion": "Cl 102 # 14A - 70 P1 - P2 - P3 y P4",
    "telefono": "3175872790",
    "correo": "nelson_infante@coomeva.com.co dianap_ospina@coomeva.com.co lauran_medina@coomeva.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "Coomeva Medicina Prepagada S.A",
    "sede": "CENTRO MEDICO COOMEVA MEDICINA PREPAGADA",
    "direccion": "Cl 102 # 14A - 70 P1 - P2 - P3 y P4",
    "telefono": "3175872790",
    "correo": "nelson_infante@coomeva.com.co dianap_ospina@coomeva.com.co lauran_medina@coomeva.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "CORPORACIÓN HOSPITALARIA JUAN CIUDAD",
    "sede": "HOSPITAL UNIVERSITARIO MAYOR-MEDERI",
    "direccion": "CL 24 # 29 45",
    "telefono": "7055999 Ext 4140",
    "correo": "ana.ulloa@mederi.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CORPORACIÓN HOSPITALARIA JUAN CIUDAD",
    "sede": "HOSPITAL UNIVERSITARIO BARRIOS UNIDOS-MEDERI",
    "direccion": "CL 66 A # 52 25",
    "telefono": "4855970 ext 6214",
    "correo": "ana.ulloa@mederi.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CPO S A",
    "sede": "CENTRO POLICLINICO DEL OLAYA",
    "direccion": "KR 20 23 23 SUR",
    "telefono": "3612888",
    "correo": "zayda.rodriguez@cpolaya.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA",
    "sede": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA",
    "direccion": "AK 68 No 68 B 31",
    "telefono": "7460909",
    "correo": "dsalud@cruzrojabogota.org.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA",
    "sede": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA SEDE NORTE",
    "direccion": "AC 134 NO. 7 B-41 PUERTA 2 Piso 1 y Piso 2, Excepto el Laboratorio Clínico y Toma de Muestras del Piso 1",
    "telefono": "7460909",
    "correo": "dsalud@cruzrojabogota.org.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA",
    "sede": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA SEDE ALQUERIA",
    "direccion": "Av. CRA. 68 No. 31 - 41 SUR",
    "telefono": "7460909",
    "correo": "dsalud@cruzrojabogota.org.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA",
    "sede": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA SEDE CALLE 73",
    "direccion": "KR 23 # 73 19 TO A PI 1-2-3",
    "telefono": "7460909 EXT 102 103",
    "correo": "dsalud@cruzrojabogota.org.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA",
    "sede": "CRUZ ROJA COLOMBIANA SECCIONAL CUNDINAMARCA Y BOGOTA SEDE CALLE 73",
    "direccion": "KR 23 # 73 19 TO A PI 1-2-3",
    "telefono": "7460909 EXT 102 103",
    "correo": "dsalud@cruzrojabogota.org.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "CUIDARTE TU SALUD S.A.S.",
    "sede": "CUIDARTE TU SALUD S.A.S",
    "direccion": "AVENIDA CALLE 63 # 69F-26",
    "telefono": "3152582777",
    "correo": "notificacionescuidarte@cuidartetusalud.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "CUIDARTE TU SALUD S.A.S.",
    "sede": "CUIDARTE TU SALUD S.A.S",
    "direccion": "AVENIDA CALLE 63 # 69F-26",
    "telefono": "3152582777",
    "correo": "notificacionescuidarte@cuidartetusalud.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "DDC IPS S.A.S",
    "sede": "DDC IPS S.A.S.",
    "direccion": "CALLE 75 N° 69K 64",
    "telefono": "3922912/3134139473",
    "correo": "ddcipssas@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "DDC IPS S.A.S",
    "sede": "DDC IPS S.A.S.",
    "direccion": "CALLE 75 N° 69K 64",
    "telefono": "3922912/3134139473",
    "correo": "ddcipssas@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "Delta Force Medics S.A.S",
    "sede": "DELTA FORCE MEDIC'S S.A.S",
    "direccion": "carrera 72 J # 36-13 sur PISO 1",
    "telefono": "3214654138",
    "correo": "deltaforcemedic905@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "EMERGENCY MANAGEMENT TRAINING SAS",
    "sede": "EMERGENCY MANAGEMENT TRAINING SAS",
    "direccion": "CARRERA 79 D # 40 A - 35 SUR PISO 1",
    "telefono": "3134283390",
    "correo": "vitalisventurasas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "EMERMEDICA S.A. SERVICIOS DE AMBULANCIA PREPAGADOS",
    "sede": "EMERMEDICA S.A. BOGOTÀ",
    "direccion": "KRA. 19 B No. 168 -35",
    "telefono": "3077098",
    "correo": "notificaciones@emermedica.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "EMERMEDICA S.A. SERVICIOS DE AMBULANCIA PREPAGADOS",
    "sede": "EMERMEDICA S.A. BOGOTÀ",
    "direccion": "KRA. 19 B No. 168 -35",
    "telefono": "3077098",
    "correo": "notificaciones@emermedica.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "EMERMEDICA S.A. SERVICIOS DE AMBULANCIA PREPAGADOS",
    "sede": "EMERMEDICA VILLA ALSACIA",
    "direccion": "calle 12b No 71d-61 LC ST",
    "telefono": "5190219",
    "correo": "notificaciones@emermedica.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "EMERMEDICA S.A. SERVICIOS DE AMBULANCIA PREPAGADOS",
    "sede": "EMERMEDICA VILLA ALSACIA",
    "direccion": "calle 12b No 71d-61 LC ST",
    "telefono": "5190219",
    "correo": "notificaciones@emermedica.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "EMPRESA DE MEDICINA INTEGRAL EMI S.A.S. SERVICIO DE AMBULANCIA PREPAGADA",
    "sede": "EMPRESA DE MEDICINA INTEGRAL EMI SAS SERVICIO DE AMBULANCIA PREPAGADA- GRUPO EMI S.A.S",
    "direccion": "KR 68 D # 18 30",
    "telefono": "6013077364 - 3133834358",
    "correo": "juan.alfonso@grupoemi.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "EMPRESA DE MEDICINA INTEGRAL EMI S.A.S. SERVICIO DE AMBULANCIA PREPAGADA",
    "sede": "EMPRESA DE MEDICINA INTEGRAL EMI SAS SERVICIO DE AMBULANCIA PREPAGADA- GRUPO EMI S.A.S",
    "direccion": "KR 68 D # 18 30",
    "telefono": "6013077364 - 3133834358",
    "correo": "juan.alfonso@grupoemi.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "EMPRESA SOCIAL DEL ESTADO HOSPITAL UNIVERSITARIO DE LA SAMARITANA",
    "sede": "EMPRESA SOCIAL DEL ESTADO HOSPITAL UNIVERSITARIO DE LA SAMARITANA",
    "direccion": "CRA 8 # 0 29 SUR",
    "telefono": "4077075 ext 10702",
    "correo": "gerencia@hus.org.co",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": true
  },
  {
    "prestador": "EMPRESA SOCIAL DEL ESTADO HOSPITAL UNIVERSITARIO DE LA SAMARITANA",
    "sede": "EMPRESA SOCIAL DEL ESTADO HOSPITAL UNIVERSITARIO DE LA SAMARITANA",
    "direccion": "CRA 8 # 0 29 SUR",
    "telefono": "4077075 ext 10702",
    "correo": "gerencia@hus.org.co",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": true
  },
  {
    "prestador": "ERMEDICALLS S.A.S",
    "sede": "ERMEDICALLS S.A.S",
    "direccion": "CALLE 87 BIS # 85 - 39",
    "telefono": "4580666 - 4580667",
    "correo": "ermedicalls@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "ERMEDICALLS S.A.S",
    "sede": "ERMEDICALLS S.A.S",
    "direccion": "CALLE 87 BIS # 85 - 39",
    "telefono": "4580666 - 4580667",
    "correo": "ermedicalls@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "FASTMED SALUD SAS SIGLA FASTMED",
    "sede": "FASTMED SALUD SAS SIGLA FASTMED",
    "direccion": "CRA 68 N Nº 36 84 SUR",
    "telefono": "3102641483",
    "correo": "fastmedsaludsas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "FUNDACION ABOOD SHAIO",
    "sede": "FUNDACION ABOOD SHAIO",
    "direccion": "DIAG 115 A # 70 C 75",
    "telefono": "2261025",
    "correo": "direcciongeneral@shaio.org",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "FUNDACION CARDIO INFANTIL INSTITUTO DE CARDIOLOGIA",
    "sede": "FUNDACION CARDIO INFANTIL INSTITUTO DE CARDIOLOGIA",
    "direccion": "CL 163 A # 13 B 60",
    "telefono": "6672727 Ext. 53304 Cel. 3183569506",
    "correo": "pcasallas@lacardio.org",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "FUNDACION HOSPITAL DE LA MISERICORDIA",
    "sede": "FUNDACION HOSPITAL DE LA MISERICORDIA",
    "direccion": "Avenida Carrera 14 No 1-65",
    "telefono": "3811970 EXT 227",
    "correo": "lidercalidad@homifundacion.org.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "FUNDACION HOSPITAL DE LA MISERICORDIA",
    "sede": "FUNDACION HOSPITAL DE LA MISERICORDIA",
    "direccion": "Avenida Carrera 14 No 1-65",
    "telefono": "3811970 EXT 227",
    "correo": "lidercalidad@homifundacion.org.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "FUNDACION HOSPITAL INFANTIL UNIVERSITARIO DE SAN JOSE",
    "sede": "FUNDACION HOSPITAL INFANTIL UNIVERSITARIO DE SAN JOSE",
    "direccion": "KR 52 # 67 A 71",
    "telefono": "4377540",
    "correo": "direccion.general@hospitalinfantildesanjose.org.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "FUNDACION SANTA FE DE BOGOTA",
    "sede": "FUNDACION SANTA FE DE BOGOTA",
    "direccion": "CL 119 # 7 75",
    "telefono": "6030303 ext. 5105",
    "correo": "adriana.urrego@fsfb.org.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "FUNDACION SANTA FE DE BOGOTA",
    "sede": "FUNDACION SANTA FE DE BOGOTA",
    "direccion": "CL 119 # 7 75",
    "telefono": "6030303 ext. 5105",
    "correo": "adriana.urrego@fsfb.org.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "GLOBAL LIFE AMBULANCIAS SAS",
    "sede": "GLOBAL LIFE AMBULANCIAS SAS",
    "direccion": "CALLE 163 # 16 C 62",
    "telefono": "3102842445",
    "correo": "calidad@glambulancias.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "GLOBAL LIFE AMBULANCIAS SAS",
    "sede": "GLOBAL LIFE AMBULANCIAS SAS",
    "direccion": "CALLE 163 # 16 C 62",
    "telefono": "3102842445",
    "correo": "calidad@glambulancias.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "Grupo AValer. S.A.S",
    "sede": "GRUPO AVALER. S.A.S SIGLA AVALER.",
    "direccion": "Calle 102 N 70-41 Bodega Piso1",
    "telefono": "3173794230",
    "correo": "avaler.medical@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "Grupo AValer. S.A.S",
    "sede": "GRUPO AVALER. S.A.S SIGLA AVALER.",
    "direccion": "Calle 102 N 70-41 Bodega Piso1",
    "telefono": "3173794230",
    "correo": "avaler.medical@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "GRUPO EMPRESARIAL JARBSALUD IPS S.A.S.",
    "sede": "GRUPO EMPRESARIAL JARBSALUD IPS S.A.S.",
    "direccion": "Calle 33 bis No. 15 - 64",
    "telefono": "4673216 - 7561334",
    "correo": "jarbsalud.gerencia@gmail.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "H&R AMBULANCIAS IPS SAS H&R AMBULANCIAS",
    "sede": "H&R AMBULANCIAS IPS S.A.S H&R AMBULANCIAS",
    "direccion": "CALLE 5 78 B-60",
    "telefono": "3477671",
    "correo": "referencia.hyrambulancias@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "HEALTH & LIFE IPS SAS SIGLA H&L UCC SAS",
    "sede": "HEALTH & LIFE IPS SAS SEDE MONTEVIDEO",
    "direccion": "Av Carrera 68 # 13 - 73",
    "telefono": "3009121102 EXT 9003",
    "correo": "mariana.rodriguez@hlips.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "HEALTH & LIFE IPS SAS SIGLA H&L UCC SAS",
    "sede": "HEALTH & LIFE IPS SAS SEDE MONTEVIDEO",
    "direccion": "Av Carrera 68 # 13 - 73",
    "telefono": "3009121102 EXT 9003",
    "correo": "mariana.rodriguez@hlips.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "HEALTH DELIVER SOLUTIONS SAS",
    "sede": "HEALTH DELIVER SOLUTIONS SAS",
    "direccion": "KR 93 # 132 - 74",
    "telefono": "3142069001",
    "correo": "724hds@gmail.com",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "Helistar SAS",
    "sede": "Helistar SAS IPS",
    "direccion": "AER El Dorado En 1 In 8 OF M-103",
    "telefono": "3143574028 / 3124506370",
    "correo": "directormedico@helistaraviacion.com",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "HELP AND LIFE MEDICAL SAS",
    "sede": "HELP AND LIFE MEDICAL SAS",
    "direccion": "AVENIDA CARRERA 50 # 4F-84 primer piso",
    "telefono": "2627499",
    "correo": "hyl.medicalsas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "HOSPITAL MILITAR CENTRAL",
    "sede": "HOSPITAL MILITAR CENTRAL",
    "direccion": "TV 3C No 49-02 El Hospital Militar presta servicios en todas las áreas del edificio central, Imagenes diagnóstica y edificio Fe en la causa EXCEPTO en el cuarto piso norte y central donde funciona servicio de terapia renal RTS",
    "telefono": "3486868 ext: 3001/3002 3158653821",
    "correo": "ayudantia@homil.gov.co",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": true
  },
  {
    "prestador": "HOSPITAL MILITAR CENTRAL",
    "sede": "HOSPITAL MILITAR CENTRAL",
    "direccion": "TV 3C No 49-02 El Hospital Militar presta servicios en todas las áreas del edificio central, Imagenes diagnóstica y edificio Fe en la causa EXCEPTO en el cuarto piso norte y central donde funciona servicio de terapia renal RTS",
    "telefono": "3486868 ext: 3001/3002 3158653821",
    "correo": "ayudantia@homil.gov.co",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": true
  },
  {
    "prestador": "HOSPITAL MILITAR CENTRAL",
    "sede": "HOSPITAL MILITAR CENTRAL",
    "direccion": "TV 3C No 49-02 El Hospital Militar presta servicios en todas las áreas del edificio central, Imagenes diagnóstica y edificio Fe en la causa EXCEPTO en el cuarto piso norte y central donde funciona servicio de terapia renal RTS",
    "telefono": "3486868 ext: 3001/3002 3158653821",
    "correo": "ayudantia@homil.gov.co",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": true
  },
  {
    "prestador": "HOSPITAL UNIVERSITARIO CLINICA SAN RAFAEL",
    "sede": "HOSPITAL UNIVERSITARIO CLINICA SAN RAFAEL",
    "direccion": "CRA 8 # 17 45 SUR",
    "telefono": "7464714 EXT. 2740",
    "correo": "direcciongeneral1@stewardcolombia.org",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "HOSPITAL UNIVERSITARIO SAN IGNACIO",
    "sede": "HOSPITAL UNIVERSITARIO SAN IGNACIO",
    "direccion": "CRA 7 # 40 62",
    "telefono": "5946161",
    "correo": "calidad@husi.org.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "INNOVA HEALTH CENTER SAS",
    "sede": "INNOVA HEALTH CENTER SAS",
    "direccion": "KR 14 # 57 - 48 SUR Local 1",
    "telefono": "2777142 - 3212409060",
    "correo": "innovahealthcentersas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "INNOVA HEALTH CENTER SAS",
    "sede": "INNOVA HEALTH CENTER SAS",
    "direccion": "KR 14 # 57 - 48 SUR Local 1",
    "telefono": "2777142 - 3212409060",
    "correo": "innovahealthcentersas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "INSTITUTO NACIONAL DE CANCEROLOGIA",
    "sede": "INSTITUTO NACIONAL DE CANCEROLOGIA",
    "direccion": "Cl 1 No 9-85",
    "telefono": "0913905012 Ext. 2000 - 2001",
    "correo": "direccion@cancer.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Ips Angeles Medicare sas sigla Ips Angeles Sas, Angeles Medicare Ips Sas",
    "sede": "IPS ANGELES MEDICARE SAS",
    "direccion": "carrera 56 a # 5 B - 68",
    "telefono": "3208283036",
    "correo": "ipsangelesmedicaresas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "J&E QUALITY HEALTH SYSTEMS SAS",
    "sede": "SEDE VILLA LUZ",
    "direccion": "CALLE 63 77 C -28",
    "telefono": "3102414265-3229494354",
    "correo": "GERENCIAQHS@GMAIL.COM",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "KOM CARE IPS S.A.S. Sigla KOM CARE IPS S.A.S.",
    "sede": "KOM CARE IPS S.A.S. Sigla KOM CARE IPS S.A.S.",
    "direccion": "Cr 11 A #98-50 P6",
    "telefono": "3134636856",
    "correo": "reportes@komcareips.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "KOONSALUD SAS",
    "sede": "KOONSALUD SAS",
    "direccion": "CR 18 P BIS No. 61 D 05 SUR P1",
    "telefono": "3102434347",
    "correo": "KOONSALUDSAS@GMAIL.COM",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "LINEA DE VIDA S.A.S",
    "sede": "LINEA DE VIDA BASE",
    "direccion": "Calle 86B #49D - 28 OFICINA 201",
    "telefono": "3158279829 - 7868160 Ext 2020",
    "correo": "marcela.sanchez@lineadevida.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "LINEA MEDICA DE AMBULANCIAS S.A.S.",
    "sede": "LINEA MEDICA DE AMBULANCIAS S.A.S.",
    "direccion": "CALLE 25 C 85 C 44 PISO 1,2 Y 3",
    "telefono": "5141414 - 3175010786",
    "correo": "amatallana@lineamedicadeambulancias.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "LINEA MEDICA DE AMBULANCIAS S.A.S.",
    "sede": "LINEA MEDICA DE AMBULANCIAS S.A.S.",
    "direccion": "CALLE 25 C 85 C 44 PISO 1,2 Y 3",
    "telefono": "5141414 - 3175010786",
    "correo": "amatallana@lineamedicadeambulancias.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "LOSCOBOS MEDICAL CENTER SAS - LOSCOBOS",
    "sede": "LOSCOBOS MEDICAL CENTER SAS - LOSCOBOS",
    "direccion": "AK 9 N° 131 A - 40",
    "telefono": "7457581 EXT 2366",
    "correo": "calidad@loscobosmc.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "MED DRIVE SAS",
    "sede": "MED DRIVE SAS",
    "direccion": "Calle 163 A 20 54 Piso 1",
    "telefono": "3124472669",
    "correo": "gerenciameddrive01@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "MEDICAL HEALTH SOCIETY S.A.S",
    "sede": "MEDICAL HEALTH SOCIETY S.A.S",
    "direccion": "CALLE 31 SUR N 51 A 11",
    "telefono": "7017381-3144512257",
    "correo": "mhsbogota@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "MEDICALL J & F SAS",
    "sede": "MEDICALL J & F SAS",
    "direccion": "AV 1 DE MAYO No. 34-64 P 1",
    "telefono": "3102052831",
    "correo": "medicalljf2022@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "Medicentro Familiar IPS SAS",
    "sede": "Medicentro Familiar IPS SAS",
    "direccion": "Calle 20 No. 98-62",
    "telefono": "3108062745-3118895118",
    "correo": "lidercalidad@clinicamedicentrofamiliar.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Medicentro Familiar IPS SAS",
    "sede": "AMBULANCIAS ALPHA",
    "direccion": "KR 99 # 20 38",
    "telefono": "3136702437 3016810008",
    "correo": "lidercalidad@medicentrofamiliarips.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Medicentro Familiar IPS SAS",
    "sede": "Clinica Medicentro Familiar sede Suba",
    "direccion": "Carrera 94B No 132A-65",
    "telefono": "3108077965",
    "correo": "lidercalidad@clinicamedicentrofamiliar.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "MEDICINA TACTICA IPS SAS SIGLA MEDITAC IPS SAS",
    "sede": "MEDICINA TACTICA IPS SAS SIGLA MEDITAC IPS SAS",
    "direccion": "CL 35 SUR # 52A - 12 PISO 1 LOCAL 2",
    "telefono": "3208625038",
    "correo": "medicinatacticaips@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "MEDIYA AG SAS",
    "sede": "MEDIYA AG SAS",
    "direccion": "CARRERA 29 No. 3-22 PRIMER PISO",
    "telefono": "3044391708",
    "correo": "mediya1018@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "PROAMBULANCIAS IPS SAS",
    "sede": "PROAMBULANCIAS IPS SAS",
    "direccion": "KR 75k # 58 B 04 SUR PI 1",
    "telefono": "3213494616",
    "correo": "proambulancias.ips@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "PROVITAL MS S.A.S",
    "sede": "PROVITAL MS S.A.S.",
    "direccion": "AC 3 No 53 F 58 P 1",
    "telefono": "7026644",
    "correo": "provitaladm21@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "RED MEDICA IPS SAS",
    "sede": "RED MEDICA IPS SAS",
    "direccion": "CALLE 71 A N 70B-35 PISO 1",
    "telefono": "6159034-6159035-3185162991",
    "correo": "gerenciaredmedicaipssas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "RED MEDICA IPS SAS",
    "sede": "RED MEDICA IPS SAS",
    "direccion": "CALLE 71 A N 70B-35 PISO 1",
    "telefono": "6159034-6159035-3185162991",
    "correo": "gerenciaredmedicaipssas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "RIO SUR SAS",
    "sede": "RIO SUR SAS",
    "direccion": "AC 26 #103 08 EN 1 IN 20 A",
    "telefono": "4139857-3138084059",
    "correo": "subgerencia@gruporiosur.com",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "S.O.S SALUD S.A.S",
    "sede": "S.O.S SALUD S.A.S",
    "direccion": "Cra 68G N° 75-71",
    "telefono": "6018000519 6014909696",
    "correo": "gerencia@sossalud.com.co",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "S.O.S SALUD S.A.S",
    "sede": "S.O.S SALUD S.A.S",
    "direccion": "Cra 68G N° 75-71",
    "telefono": "6018000519 6014909696",
    "correo": "gerencia@sossalud.com.co",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "SALVID SALUD SAS",
    "sede": "SALVID SALUD SAS",
    "direccion": "CALLE 130C Nº 90-20",
    "telefono": "3229144955",
    "correo": "SALVIDSALUDSAS@GMAIL.COM",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "SAMBUCI SAS",
    "sede": "SAMBUCI SAS",
    "direccion": "CL 71 A 68 F 26 P1",
    "telefono": "3232255717",
    "correo": "sambucisas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "SERBIOMEGA AMBULANCIAS SAS",
    "sede": "SERBIOMEGA AMBULANCIAS SAS",
    "direccion": "Cr 71 D No 72 24",
    "telefono": "3156886128",
    "correo": "serbiomega.ambulancias@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "SERBIOMEGA AMBULANCIAS SAS",
    "sede": "SERBIOMEGA AMBULANCIAS SAS",
    "direccion": "Cr 71 D No 72 24",
    "telefono": "3156886128",
    "correo": "serbiomega.ambulancias@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "SERVIAMBULANCIAS 247 SAS",
    "sede": "SERVIAMBULANCIAS 247 SEDE BOGOTA",
    "direccion": "Cl 48 A Sur No. 77 V 34 P 1",
    "telefono": "3006127792",
    "correo": "serviambulancias24@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "Servicio y Atencion de Emergencia Medica SAS Sigla Ambulancias SAEM SAS",
    "sede": "Servicio y Atencion de Emergencia Medica SAS Sigla Ambulancias SAEM SAS",
    "direccion": "CALLE 49 B SUR No 28 - 47 PISO 1 LOCAL 1",
    "telefono": "3007399261",
    "correo": "ambulanciassaem@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "SERVICIOS AEREOS PANAMERICANOS SAS",
    "sede": "SERVICIOS AEREOS PANAMERICANOS",
    "direccion": "EL DORADO VIA CATAM EN 6 HG 39",
    "telefono": "7434161",
    "correo": "adriana.escobar@sarpa.com.co",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "SERVICIOS BIOMEDICOS INGENIERIA LTDA SERBIOMED LTDA",
    "sede": "SERVICIOS BIOMEDICOS INGENIERIA LTDA SERBIOMED LTDA",
    "direccion": "Calle 74 #75-27/37",
    "telefono": "3506002364-6316026-4903579-4900083",
    "correo": "gerencia@serbiomedambulancias.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "SERVICIOS BIOMEDICOS INGENIERIA LTDA SERBIOMED LTDA",
    "sede": "SERVICIOS BIOMEDICOS INGENIERIA LTDA SERBIOMED LTDA",
    "direccion": "Calle 74 #75-27/37",
    "telefono": "3506002364-6316026-4903579-4900083",
    "correo": "gerencia@serbiomedambulancias.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "Servicios de Salud IPS Suramericana S.A.S",
    "sede": "SALUD SURA CALLE 100 BOGOTA",
    "direccion": "Cl. 100 No. 19 A - 35",
    "telefono": "(1) 487 38 88 / 3164625445",
    "correo": "rqext@suramericana.com.co / llbenavidesm@sura.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "servicios medicos prioritarios sas",
    "sede": "servicios medicos prioritarios sas",
    "direccion": "cra 95 N 146a - 31",
    "telefono": "3016572232",
    "correo": "info@serviciosmedicosprioritarios.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "SOCIEDAD DE CIRUGIA DE BOGOTA HOSPITAL DE SAN JOSE",
    "sede": "Sociedad de Cirugía de Bogotá - Hospital de San José",
    "direccion": "CL 10 No. 18 - 75",
    "telefono": "3538000 ext 523 o 509",
    "correo": "calidad@hospitaldesanjose.org.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SOCIEDAD MEDICA ALCALA SAS",
    "sede": "SOCIEDAD MEDICA ALCALA SAS",
    "direccion": "AVENIDA CARRERA 19 No 135-24",
    "telefono": "3232255717-3114849286",
    "correo": "calidad@smaclinica.com",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SOCIEDAD MEDICA DE ORTOPEDIA Y ACCIDENTES LABORALES S A",
    "sede": "CLINICA DE ORTOPEDIA Y ACCIDENTES LABORALES",
    "direccion": "Calle 6 A # 70 - 06",
    "telefono": null,
    "correo": "gerenciasmo@coal.clinic",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SANTA CLARA HOSPITAL UNIVERSITARIO",
    "direccion": "CARRERA 14 B NUMERO 1-45 SUR",
    "telefono": "3282828 ext 18191, 18000, 18151",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SAN BLAS",
    "direccion": "TRANSVERSAL 5 ESTE NUMERO 19-50 SUR",
    "telefono": "3282828 EXT 13192, 13941,13620",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SAN BLAS",
    "direccion": "TRANSVERSAL 5 ESTE NUMERO 19-50 SUR",
    "telefono": "3282828 EXT 13192, 13941,13620",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SAN BLAS",
    "direccion": "TRANSVERSAL 5 ESTE NUMERO 19-50 SUR",
    "telefono": "3282828 EXT 13192, 13941,13620",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD PERSEVERANCIA",
    "direccion": "CARRERA 5 NUMERO 33 A-45",
    "telefono": "3282828 ETX 25181,25191",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SAMPER MENDOZA",
    "direccion": "CARRERA 22 NUMERO 22 A -26",
    "telefono": "3282828 EXT 19191,19181,19611",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD JORGE ELIECER GAITAN",
    "direccion": "CARRERA 4 A ESTE # 5-20",
    "telefono": "3282828 ETX 16912, 16611,16571",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD DIANA TURBAY",
    "direccion": "carrera 1f #48x 40 sur",
    "telefono": "3282828",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD CHIRCALES",
    "direccion": "TRANSVERSAL 5 L BIS NUMERO 48 F- 69 SUR",
    "telefono": "3282828 EXT 21341, 21181,21621",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD OLAYA",
    "direccion": "CARRERA 21 NUMERO 22-51 SUR",
    "telefono": "3282828 EXT 24192,24191,24851",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD VICTORIA",
    "direccion": "DIAGONAL 39 SUR NUMERO 3-20 ESTE",
    "telefono": "3282828 EXT 14131, 14132, 14192",
    "correo": "radicacionmedioselectronicos@subredcentrooriente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SIMÓN BOLÍVAR",
    "direccion": "CALLE 165 # 7 06",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SIMÓN BOLÍVAR",
    "direccion": "CALLE 165 # 7 06",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SIMÓN BOLÍVAR",
    "direccion": "CALLE 165 # 7 06",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD ENGATIVÁ CALLE 80",
    "direccion": "TRANSVERSAL 100 A # 80 A - 50",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD ENGATIVÁ CALLE 80",
    "direccion": "TRANSVERSAL 100 A # 80 A - 50",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD EMAUS",
    "direccion": "CALLE 64 C # 121 - 76",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD CENTRO DE SERVICIOS ESPECIALIZADO",
    "direccion": "KR 104 Nº 152C-50",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD GAITANA I",
    "direccion": "TRANSVERSAL 126 Nº 134-88",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E.S.E",
    "sede": "UNIDAD DE SERVICIOS DE SALUD CHAPINERO",
    "direccion": "Calle 66 No 15-41",
    "telefono": "4431790",
    "correo": "subrednorte@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD EL TUNAL",
    "direccion": "CR 20 47B-35 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD EL TUNAL",
    "direccion": "CR 20 47B-35 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD MEISSEN",
    "direccion": "KR 18 B No. 60 G - 36 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD MEISSEN",
    "direccion": "KR 18 B No. 60 G - 36 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD MEISSEN",
    "direccion": "KR 18 B No. 60 G - 36 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD AMBULATORIA TUNJUELITO",
    "direccion": "AV CARACAS No. 51 - 21 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD AMBULATORIA TUNJUELITO",
    "direccion": "AV CARACAS No. 51 - 21 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD AMBULATORIA TUNJUELITO",
    "direccion": "AV CARACAS No. 51 - 21 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD JERUSALEN",
    "direccion": "CL 77 No. 85 B - 13 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD VISTA HERMOSA",
    "direccion": "KR 18 C No. 66 A - 55 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD USME",
    "direccion": "KR 13 No. 135 A - 42 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD USME",
    "direccion": "KR 13 No. 135 A - 42 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD USME",
    "direccion": "KR 13 No. 135 A - 42 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SANTA LIBRADA I",
    "direccion": "KR 9 B No. 75 - 49 SUR",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SAN JUAN DE SUMAPÁZ",
    "direccion": "Corregimiento San Juan de Sumapáz",
    "telefono": "3219007751",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD SAN JUAN DE SUMAPÁZ",
    "direccion": "Corregimiento San Juan de Sumapáz",
    "telefono": "3219007751",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "UNIDAD DE SERVICIOS DE SALUD NAZARETH",
    "direccion": "Corregimiento de Nazareth de Sumapaz",
    "telefono": "3108879305",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR E.S.E.",
    "sede": "HOSPITAL DE USME",
    "direccion": "carrera 5 Este # 110-11 Sur",
    "telefono": "7300000 Opción 0",
    "correo": "subredsur@saludcapital.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Hospital Occidente de Kennedy",
    "direccion": "TV 74 F # 40 B 54 SUR",
    "telefono": "3849160",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Hospital Occidente de Kennedy",
    "direccion": "TV 74 F # 40 B 54 SUR",
    "telefono": "3849160",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Hospital Occidente de Kennedy",
    "direccion": "TV 74 F # 40 B 54 SUR",
    "telefono": "3849160",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Hospital Pediátrico Tintal",
    "direccion": "CALLE 10 # 86 - 58",
    "telefono": "5550950",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Centro de Salud Patio Bonito",
    "direccion": "Diagonal 38 sur No. 82 - 30",
    "telefono": "4547018",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Centro de Salud Trinidad Galán",
    "direccion": "Carrera 60 No. 4 - 15",
    "telefono": "2607876",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Hospital Fontibón",
    "direccion": "Carrera 99 No. 16i - 41",
    "telefono": "4860033",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Hospital Fontibón",
    "direccion": "Carrera 99 No. 16i - 41",
    "telefono": "4860033",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Hospital Fontibón",
    "direccion": "Carrera 99 No. 16i - 41",
    "telefono": "4860033",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Subred Integrada de Servicios de Salud Sur Occidente E.S.E",
    "sede": "Hospital de Bosa",
    "direccion": "Calle 73 Sur # 100 A - 53",
    "telefono": "6013849160",
    "correo": "contactenos@subredsuroccidente.gov.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "SYG AMBULANCIAS S.A.S.",
    "sede": "SYG AMBULANCIAS S.A.S.",
    "direccion": "CL 164B # 4 47 PI 1",
    "telefono": "3208555096 - 3213353137",
    "correo": "sygambulancias@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "SYG AMBULANCIAS S.A.S.",
    "sede": "SYG AMBULANCIAS S.A.S.",
    "direccion": "CL 164B # 4 47 PI 1",
    "telefono": "3208555096 - 3213353137",
    "correo": "sygambulancias@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "UNIDAD MEDICA ONCOLOGICA ONCOLIFE IPS SAS",
    "sede": "UNIDAD MEDICA ONCOLOGICA ONCOLIFE IPS SAS",
    "direccion": "AV Carrera 45 # 104A 87/91",
    "telefono": "5803973-3178061653",
    "correo": "calidad1@oncolife.com.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "UNIDAD MEDICA Y DE DIAGNOSTICO S.A",
    "sede": "CENTRO MÉDICO SEDE TORRE COLMÉDICA SANTA BÁRBARA",
    "direccion": "AK 45 NO. 122 - 96 Piso 1 Excepto Consultorios A y B - Piso 2 - Piso 4 - Piso 6 - Piso 7",
    "telefono": "3176551904 - 3212535796",
    "correo": "NotificacionesJudiciales@umd.com.co",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "UNIVERSIDAD NACIONAL DE COLOMBIA",
    "sede": "AREA DE SALUD DE BIENESTAR DE LA UNIVERSIDAD NACIONAL DE COLOMBIA SEDE BOGOTA",
    "direccion": "KR 30 # 45 03 ED 426 PI 1 ED DE GENÉTICA",
    "telefono": "(57)(1) 3165520/10",
    "correo": "areasalud_bog@unal.edu.co",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "vertical salud urgencias y emergencias s.a.s sigla VSUE",
    "sede": "vertical salud urgencias y emergencias s.a.s sigla vsue",
    "direccion": "carrera 25 # 23-11 sur",
    "telefono": "3728663-3142124166",
    "correo": "verticaljc@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "VIDEO OFFICE MEDICALL IPS S.A.S. - VOM",
    "sede": "VIDEO OFFICE MEDICALL IPS S.A.S. - VOM",
    "direccion": "CL 37 D SUR # 68 L 32 PI 1, PI 4 y PI 5 \"ARCHIVO\"",
    "telefono": "7103384 - 3133484737",
    "correo": "videoofficemedicall@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "VIDEO OFFICE MEDICALL IPS S.A.S. - VOM",
    "sede": "VIDEO OFFICE MEDICALL IPS S.A.S. - VOM",
    "direccion": "CL 37 D SUR # 68 L 32 PI 1, PI 4 y PI 5 \"ARCHIVO\"",
    "telefono": "7103384 - 3133484737",
    "correo": "videoofficemedicall@gmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "VIRREY SOLIS IPS. S.A.",
    "sede": "VIRREY SOLIS I.P.S S.A. AMERICAS",
    "direccion": "AV LAS AMERICAS # 66 A 27 PISO 1 PISO 2 BLOQUE SUR",
    "telefono": "4473535 EXT 278, 476, 248",
    "correo": "calidad@virreysolisips.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "VIRREY SOLIS IPS. S.A.",
    "sede": "VIRREY SOLIS IPS S.A - CLINICA SUBA",
    "direccion": "AC 145 # 95 B - 22",
    "telefono": "4473535 EXT 278, 476, 248",
    "correo": "calidad@virreysolisips.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "VIRREY SOLIS IPS. S.A.",
    "sede": "VIRREY SOLIS IPS.S.A. CALLE 98",
    "direccion": "KR 49 No 98 A 28",
    "telefono": "4473535 EXT 278, 476, 248",
    "correo": "calidad@virreysolisips.com.co",
    "nit": null,
    "tab": false,
    "tam": false,
    "urgencias": true
  },
  {
    "prestador": "Visión medica de Ambulancias SAS",
    "sede": "VISION MEDICA DE AMBULANCIAS SAS",
    "direccion": "CL 25 SUR # 69C 69 PISO 1- ENTRADA 1",
    "telefono": "6013061090 3152235497",
    "correo": "visionmedicadeambulancias@gmail.com",
    "nit": null,
    "tab": false,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "VITAL CARE S.O.S S.A.S",
    "sede": "VITAL CARE S.O.S S.A.S",
    "direccion": "CR 71 NO. 65 B 04 PRIMER PISO",
    "telefono": "3217561941",
    "correo": "vitalcaresos3@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "VITAL LIFE SAS",
    "sede": "VITAL LIFE SAS",
    "direccion": "CALLE 102 A NO. 70G-19 y 70G-21",
    "telefono": "2719676 - 7579602-7429502 -2269505 - 2269506",
    "correo": "alixrruiz-bello@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "VITAL LIFE SAS",
    "sede": "VITAL LIFE SAS",
    "direccion": "CALLE 102 A NO. 70G-19 y 70G-21",
    "telefono": "2719676 - 7579602-7429502 -2269505 - 2269506",
    "correo": "alixrruiz-bello@hotmail.com",
    "nit": null,
    "tab": true,
    "tam": true,
    "urgencias": false
  },
  {
    "prestador": "VITAL TIME D Y G SAS",
    "sede": "VITAL TIME D Y G SAS SEDE BOGOTA",
    "direccion": "CALLE 40 A SUR # 90 A -09 P 1",
    "telefono": "3239979437",
    "correo": "dygvitaltimesas@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  },
  {
    "prestador": "WORLD IN AMBULANCE SERVICES SAS",
    "sede": "WORLD IN AMBULANCE SERVICES SAS",
    "direccion": "KR 77 BIS 70 12 PI 1",
    "telefono": "3045528005",
    "correo": "wordambulance@gmail.com",
    "nit": null,
    "tab": true,
    "tam": false,
    "urgencias": false
  }
];
